version: '3.5'

services:
  osticket-app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./osticket:/var/www/html      
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${APP_PORT}:80
    networks:
      - osticket-network

  osticket-mysql:
    image: mysql:5.7
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
      - ./configs/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
    networks:
      - osticket-network

networks:
  osticket-network:
    driver: bridge