version: '3.5'

services:
  app:
    build: .
    container_name: app
    restart: unless-stopped
    volumes:
      - ./osticket:/var/www/html      
      - ./configs/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${HOST_EXT_PORT}:${HOST_INT_PORT}
    networks:
      - osticket-network

  osticket-mysql:
    image: mysql:5.7
    container_name: osticket-mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_EXT_PORT}:${MYSQL_INT_PORT}
    volumes:
      - ./configs/mysql/database:/var/lib/mysql
      - ./configs/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - osticket-network

networks:
  osticket-network:
    driver: bridge