version: '3.5'

services:
  osticket-app:
    build:
      context: '.'
      args:
        uid: ${UID}
    container_name: osticket-app
    restart: unless-stopped
    environment:
      - APACHE_RUN_USER=#${UID}
      - APACHE_RUN_GROUP=#${UID}
    volumes:
      - /osticket:/var/www/html
      - /configs/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${HOST_EXT_PORT}:${HOST_INT_PORT}
    networks:
      - osticket-network

  osticket-mysql:
    image: mysql:5.7
    container_name: osticket-mysql
    restart: unless-stopped
    ports:
      - ${MYSQL_EXT_PORT}:${MYSQL_INT_PORT}
    volumes:
      - /configs/mysql/database:/var/lib/mysql
      - /configs/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    networks:
      - osticket-network

networks:
  osticket-network:
    driver: bridge
